# Generated by Django 5.0 on 2023-12-06 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CATName", models.CharField(max_length=50, verbose_name="Name")),
                ("CATDesc", models.TextField(verbose_name="Description")),
                (
                    "CATParent",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"CATParent__isnull": True},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.category",
                        verbose_name="MAin Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "PRDName",
                    models.CharField(max_length=50, verbose_name="Product Name"),
                ),
                ("PRDDesc", models.TextField(verbose_name="Product Description")),
                (
                    "PRDImage",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_image/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "PRDPrice",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Price"
                    ),
                ),
                (
                    "PRDDiscountPrice",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Discount Price",
                    ),
                ),
                (
                    "PRDCost",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Cost"
                    ),
                ),
                (
                    "PRDCreated",
                    models.DateTimeField(auto_now=True, verbose_name="Created at"),
                ),
                (
                    "PRDSlug",
                    models.SlugField(blank=True, null=True, verbose_name="Product URL"),
                ),
                (
                    "PRDISNew",
                    models.BooleanField(default=True, verbose_name="New Product"),
                ),
                (
                    "PRDISBestSeller",
                    models.BooleanField(default=False, verbose_name="Best Seller"),
                ),
                (
                    "PRDCategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
