# Generated by Django 4.2.7 on 2023-12-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_prdauthor_alter_product_prdname'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CATImg',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='category',
            name='CATSlug',
            field=models.SlugField(blank=True, null=True, verbose_name='Category URL'),
        ),
    ]
