# Generated by Django 4.2.7 on 2023-12-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone Number"
            ),
        ),
    ]
